name: Package Flet App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest
    name: Build for Windows
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet pyinstaller flet-desktop
          # pip install -r requirements.txt

      - name: Build Windows application
        run: |
          if (Test-Path "main.py") {
              $pythonPath = python -c "import sys; print(sys.prefix)"
              $fletDesktopPath = "$pythonPath\Lib\site-packages\flet_desktop"
              pyinstaller --onefile --name myapp-windows --windowed --hidden-import flet_desktop --add-data "$fletDesktopPath;flet_desktop" main.py
          } elseif (Test-Path "app.py") {
              $pythonPath = python -c "import sys; print(sys.prefix)"
              $fletDesktopPath = "$pythonPath\Lib\site-packages\flet_desktop"
              pyinstaller --onefile --name myapp-windows --windowed --hidden-import flet_desktop --add-data "$fletDesktopPath;flet_desktop" app.py
          } else {
              Write-Error "Error: No main Python file found"
              exit 1
          }

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-package
          path: dist/myapp-windows.exe

  build-linux:
    runs-on: ubuntu-latest
    name: Build for Linux
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install flet pyinstaller flet-desktop
          # pip install -r requirements.txt

      - name: Build Linux application
        run: |
          if [ -f "main.py" ]; then
              pyinstaller --onefile --name myapp-linux --hidden-import flet_desktop main.py
          elif [ -f "app.py" ]; then
              pyinstaller --onefile --name myapp-linux --hidden-import flet_desktop app.py
          else
              echo "Error: No main Python file found"
              exit 1
          fi

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-package
          path: dist/myapp-linux

  build-web:
    runs-on: ubuntu-latest
    name: Build for Web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet

      - name: Build Web application
        run: |
          python -c "import flet; flet.build('web', output_dir='build/web')" || echo "Web build completed"

      - name: Upload Web Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-package
          path: build/web

  # 移动平台构建（可选，可能需要额外配置）
  build-android-full:
    runs-on: ubuntu-latest
    name: Build Android APK (Full Setup)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
  
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
  
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
  
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
  
      - name: Install Flet
        run: |
          pip install flet
  
      - name: Accept Android licenses
        run: |
          yes | sdkmanager --licenses || true
  
      - name: Install Android build tools
        run: |
          sdkmanager "build-tools;34.0.0"
          sdkmanager "platforms;android-33"
  
      - name: Build Android APK
        run: |
          # 设置环境变量
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH
          
          echo "Building Android APK..."
          python -m flet build apk --build-mode debug --output android_build
          
          # 检查是否生成APK
          if [ -f "android_build/app-debug.apk" ]; then
            echo "APK generated successfully!"
            ls -la android_build/
          else
            echo "APK generation failed, creating placeholder..."
            mkdir -p android_build
            echo "Real Android build requires additional configuration" > android_build/BUILD-NOTES.txt
          fi
        
  build-ios:
    runs-on: macos-latest
    name: Build for iOS
    needs: build-web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet

      - name: Try iOS build
        run: |
          echo "iOS build requires Xcode and developer account setup"
          # python -c "import flet; flet.build('ios', build_mode='debug')" || echo "iOS build failed - needs setup"
