name: Package Flet App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # 指定你的 Python 版本

      - name: Install Flet
        run: |
          pip install flet

      - name: Install dependencies (if any)
        run: |
          # 如果有 requirements.txt 文件，取消下面的注释
          # pip install -r requirements.txt

      - name: Package for Desktop
        run: |
          flet package --target desktop

      - name: Package for Web
        run: |
          flet package --target web

      - name: Package for Mobile
        run: |
          flet package --target mobile

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: flet-packages
          path: dist/*
