name: Package Flet App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Flet
        run: |
          pip install flet

      - name: Install pyinstaller
        run: |
          pip install pyinstaller
          

      - name: Debug Flet installation
        run: |
          python --version
          pip show flet
          flet --version
          flet --help

      - name: Check pack command syntax
        run: |
          flet pack --help

      - name: Install dependencies (if any)
        run: |
          # 如果有 requirements.txt 文件，取消下面的注释
          # pip install -r requirements.txt

      - name: Install Flet CLI (if needed)
        run: |
          pip install flet-cli

      - name: Package for Windows
        run: |
          flet build windows main.py

      - name: Package for Linux
        run: |
          flet build linux main.py

      - name: Package for macOS
        run: |
          flet build macos main.py

      - name: Package for Web
        run: |
          flet build --name myapp --dir main.py --build web

      - name: Package for Mobile (Android)
        run: |
          flet build --name myapp --dir main.py --build android

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: flet-packages
          path: build/*
